from .auto_role import AutoRole
from .feature_request import FeatureRequest
from .kick_malabar import KickMalabar
from .kick_paglops import KickPaglops
from .kick_t4g1 import KickT4g1
from .opinion import Opinion
from .ping import Ping
from .popof import Popof
from .score_tracker import ScoreTracker
from .self_role import SelfRole
from .sound_effects import SoundEffects
